(library
 (public_name rayforce)
 (foreign_stubs
  (language c)
  (names rayforce_stubs)
  (flags
   :standard
   (:include c_flags.sexp)
   -Wall
   -Werror))
 (c_library_flags
  :standard
  (:include c_library_flags.sexp))
 (libraries bigarray))

(rule
 (targets c_flags.sexp c_library_flags.sexp)
 (deps
  (env_var RAYFORCE_LIBDIR)
  (env_var RAYFORCE_INCDIR))
 (action
  (run ./config/discover.exe)))
